package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/google/uuid"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

type User struct {
	ID        uint       `gorm:"primaryKey" json:"id"`
	UUID      string     `gorm:"uniqueIndex" json:"uuid"`
	TgID      int64      `json:"tg_id"`
	Status    string     `gorm:"default:'active'" json:"status"`
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt *time.Time `json:"expires_at"`
}

// Device replaces username/email with a Shadow ID token for the mobile app
type Device struct {
	ID        uint       `gorm:"primaryKey" json:"id"`
	ShadowID  string     `gorm:"uniqueIndex" json:"shadow_id"` // Generated by App
	Token     string     `gorm:"uniqueIndex" json:"token"`     // Secret token for API calls
	Status    string     `gorm:"default:'active'" json:"status"`
	CreatedAt time.Time  `json:"created_at"`
	PaidUntil *time.Time `json:"paid_until"`
}

var (
	db          *gorm.DB
	xrayManager *XrayManager
)

func main() {
	// Setup stdout logging only (Security Phase 3.3: Disable persistent disk logging)
	log.SetOutput(os.Stdout)
	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)

	log.Println("[STARTUP] VPN Backend starting...")

	// Database
	var err error
	db, err = gorm.Open(sqlite.Open("/app/data/vpn.db"), &gorm.Config{})
	if err != nil {
		log.Fatalf("[STARTUP] Failed db: %v", err)
	}
	db.AutoMigrate(&User{}, &Device{})
	log.Println("[STARTUP] Database connected")

	// Xray gRPC manager
	xrayAddr := os.Getenv("XRAY_API_ADDR")
	if xrayAddr == "" {
		xrayAddr = "xray:10085"
	}
	xrayManager, err = NewXrayManager(xrayAddr)
	if err != nil {
		log.Fatalf("[STARTUP] Failed xray mgr: %v", err)
	}
	log.Printf("[STARTUP] Connected to Xray gRPC at %s", xrayAddr)

	// Sync existing users to Xray on startup
	syncUsersOnStartup()

	// Fiber app
	app := fiber.New(fiber.Config{
		DisableStartupMessage: true,
	})
	app.Use(cors.New())

	// Auth middleware
	adminToken := os.Getenv("ADMIN_TOKEN")
	authMiddleware := func(c *fiber.Ctx) error {
		if adminToken == "" {
			return c.Next() // Allow if no token configured
		}
		authHeader := c.Get("Authorization")
		if authHeader != "Bearer "+adminToken {
			return c.Status(401).JSON(fiber.Map{"error": "Unauthorized"})
		}
		return c.Next()
	}

	// Routes
	app.Get("/api/health", handleHealth)

	// Public Client Portal API
	app.Get("/api/client/:uuid", handleGetClientConfig)

	// Panel API (Protected)
	api := app.Group("/api", authMiddleware)
	api.Post("/keys", handleCreateKey)
	api.Delete("/keys/:uuid", handleDeleteKey)
	api.Delete("/users", handleDeleteAllUsers)
	api.Get("/logs/download", handleDownloadLogs)
	api.Get("/users", handleListUsers)

	// Mobile App API v1 (Zero-Knowledge Auth)
	v1 := app.Group("/v1")
	v1.Post("/auth/register", handleMobileRegister)
	v1.Post("/auth/login", handleMobileLogin)
	v1.Get("/vpn/servers", handleMobileGetServers) // Needs device token
	v1.Get("/vpn/connect-config", handleMobileGetConfig)

	// Start Expiration Daemon (Phase 2.3)
	go func() {
		ticker := time.NewTicker(time.Minute * 10) // check every 10 min
		for range ticker.C {
			log.Println("[DAEMON] Running expiration purge...")
			var expired []Device
			db.Where("status = ? AND paid_until < ?", "active", time.Now()).Find(&expired)
			for _, dev := range expired {
				dev.Status = "expired"
				db.Save(&dev)
				// Find associated VPN key
				var vpnUser User
				if err := db.Where("tg_id = ?", int64(dev.ID)).First(&vpnUser).Error; err == nil {
					vpnUser.Status = "disabled"
					db.Save(&vpnUser)
					xrayManager.RemoveUser("dev_" + vpnUser.UUID[:6])
					log.Printf("[DAEMON] Revoked VPN access for shadowID %s", dev.ShadowID[:8])
				}
			}
		}
	}()

	// Graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		log.Println("[STARTUP] Listening on :3000")
		if err := app.Listen(":3000"); err != nil {
			log.Printf("[ERROR] Server: %v", err)
		}
	}()

	<-quit
	log.Println("[SHUTDOWN] Graceful shutdown initiated...")
	_ = app.Shutdown()
	_ = xrayManager.Close()
	sqlDB, _ := db.DB()
	_ = sqlDB.Close()
	log.Println("[SHUTDOWN] Complete")
}

// syncUsersOnStartup re-registers all active users from DB into Xray
// This ensures VPN keys survive Xray restarts
func syncUsersOnStartup() {
	var users []User
	db.Where("status = ?", "active").Find(&users)
	synced := 0
	for _, u := range users {
		err := xrayManager.AddUser(u.UUID, "user_"+u.UUID[:6])
		if err != nil {
			log.Printf("[SYNC] Failed user %s: %v", u.UUID[:8], err)
		} else {
			synced++
		}
	}
	log.Printf("[SYNC] Synced %d/%d active users to Xray", synced, len(users))
}

type CreateKeyResponse struct {
	ClientURL string `json:"client_url"`
	VlessTCP  string `json:"vless_tcp"`
	VlessGRPC string `json:"vless_grpc"`
}

type ClientStatusResponse struct {
	UUID      string     `json:"uuid"`
	Status    string     `json:"status"`
	ExpiresAt *time.Time `json:"expires_at"`
	VlessTCP  string     `json:"vless_tcp"`
	VlessGRPC string     `json:"vless_grpc"`
}

func handleGetClientConfig(c *fiber.Ctx) error {
	reqUUID := c.Params("uuid")
	var user User
	if err := db.Where("uuid = ?", reqUUID).First(&user).Error; err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Client not found"})
	}

	serverIP := os.Getenv("SERVER_IP")
	pubKey := os.Getenv("REALITY_PUBLIC_KEY")
	shortID := os.Getenv("REALITY_SHORT_ID")

	vlessTCP := fmt.Sprintf(
		"vless://%s@%s:443?type=tcp&security=reality&pbk=%s&fp=chrome&sni=addons.mozilla.org&sid=%s&spx=%%2F&flow=xtls-rprx-vision#VPN-Standard-%s",
		user.UUID, serverIP, pubKey, shortID, user.UUID[:4],
	)

	vlessGRPC := fmt.Sprintf(
		"vless://%s@%s:8443?type=grpc&security=reality&pbk=%s&fp=chrome&sni=vk.com&sid=%s&serviceName=VpnService#VPN-Stealth-RU-%s",
		user.UUID, serverIP, pubKey, shortID, user.UUID[:4],
	)

	return c.JSON(ClientStatusResponse{
		UUID:      user.UUID,
		Status:    user.Status,
		ExpiresAt: user.ExpiresAt,
		VlessTCP:  vlessTCP,
		VlessGRPC: vlessGRPC,
	})
}

func handleCreateKey(c *fiber.Ctx) error {
	newUUID := uuid.New().String()
	exp := time.Now().AddDate(0, 1, 0) // default 30 days
	user := User{
		UUID:      newUUID,
		Status:    "active",
		CreatedAt: time.Now(),
		ExpiresAt: &exp,
	}

	if err := db.Create(&user).Error; err != nil {
		log.Printf("[ERROR] DB create: %v", err)
		return c.Status(500).SendString("db error")
	}

	email := "user_" + newUUID[:6]
	if err := xrayManager.AddUser(newUUID, email); err != nil {
		log.Printf("[ERROR] gRPC AddUser: %v", err)
		return c.Status(500).SendString("xray error: " + err.Error())
	}

	serverIP := os.Getenv("SERVER_IP")
	pubKey := os.Getenv("REALITY_PUBLIC_KEY")
	shortID := os.Getenv("REALITY_SHORT_ID")

	vlessTCP := fmt.Sprintf(
		"vless://%s@%s:443?type=tcp&security=reality&pbk=%s&fp=chrome&sni=addons.mozilla.org&sid=%s&spx=%%2F&flow=xtls-rprx-vision#VPN-Standard-%s",
		newUUID, serverIP, pubKey, shortID, newUUID[:4],
	)

	vlessGRPC := fmt.Sprintf(
		"vless://%s@%s:8443?type=grpc&security=reality&pbk=%s&fp=chrome&sni=vk.com&sid=%s&serviceName=VpnService#VPN-Stealth-RU-%s",
		newUUID, serverIP, pubKey, shortID, newUUID[:4],
	)

	clientURL := fmt.Sprintf("http://%s:8080/client/%s", serverIP, newUUID)

	log.Printf("[KEY] Created key %s for email %s", newUUID[:8], email)
	return c.JSON(CreateKeyResponse{
		ClientURL: clientURL,
		VlessTCP:  vlessTCP,
		VlessGRPC: vlessGRPC,
	})
}

func handleDeleteKey(c *fiber.Ctx) error {
	reqUUID := c.Params("uuid")

	// Find the user to get email for Xray removal
	var user User
	if err := db.Where("uuid = ?", reqUUID).First(&user).Error; err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "User not found"})
	}

	// 1. Remove from DB
	if err := db.Delete(&user).Error; err != nil {
		return c.Status(500).SendString("db delete error")
	}

	// 2. Remove from Xray
	email := "user_" + reqUUID[:6]
	if err := xrayManager.RemoveUser(email); err != nil {
		log.Printf("[ERROR] Xray RemoveUser: %v", err)
	}

	log.Printf("[KEY] Deleted key %s", reqUUID[:8])
	return c.SendStatus(200)
}

func handleDeleteAllUsers(c *fiber.Ctx) error {
	var users []User
	if err := db.Find(&users).Error; err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "Failed to fetch users"})
	}

	deletedCount := 0
	for _, user := range users {
		email := "user_" + user.UUID[:6]
		// Remove from Xray
		xrayManager.RemoveUser(email)
		// Remove from DB
		db.Delete(&user)
		deletedCount++
	}

	log.Printf("[KEY] Bulk deleted %d users", deletedCount)
	return c.JSON(fiber.Map{"message": fmt.Sprintf("Deleted %d users", deletedCount)})
}

func handleDownloadLogs(c *fiber.Ctx) error {
	logPath := "/app/data/app.log"
	if _, err := os.Stat(logPath); os.IsNotExist(err) {
		return c.Status(404).SendString("No logs found")
	}
	c.Set("Content-Disposition", "attachment; filename=server-logs.txt")
	c.Set("Content-Type", "text/plain; charset=utf-8")
	return c.SendFile(logPath)
}

func handleListUsers(c *fiber.Ctx) error {
	var users []User
	db.Order("id desc").Limit(50).Find(&users)
	return c.JSON(users)
}

func handleHealth(c *fiber.Ctx) error {
	var count int64
	db.Model(&User{}).Where("status = ?", "active").Count(&count)
	return c.JSON(fiber.Map{
		"status":       "ok",
		"active_users": count,
		"server_ip":    os.Getenv("SERVER_IP"),
	})
}

// ---------------------------------------------------------
// Phase 2.1: Mobile App API v1 (Shadow Identity)
// ---------------------------------------------------------

type RegisterRequest struct {
	ShadowID string `json:"shadow_id"`
}

func handleMobileRegister(c *fiber.Ctx) error {
	var req RegisterRequest
	if err := c.BodyParser(&req); err != nil || req.ShadowID == "" {
		return c.Status(400).JSON(fiber.Map{"error": "invalid format, expected shadow_id"})
	}

	// Try to find existing
	var existing Device
	if err := db.Where("shadow_id = ?", req.ShadowID).First(&existing).Error; err == nil {
		return c.JSON(fiber.Map{"token": existing.Token, "status": existing.Status})
	}

	// Create new
	newToken := uuid.New().String()
	newDev := Device{
		ShadowID: req.ShadowID,
		Token:    newToken,
		Status:   "created",
		CreatedAt: time.Now(),
	}
	if err := db.Create(&newDev).Error; err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "db error"})
	}

	return c.JSON(fiber.Map{"token": newToken, "status": "created"})
}

func handleMobileLogin(c *fiber.Ctx) error {
	var req struct {
		Token string `json:"token"`
	}
	if err := c.BodyParser(&req); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "bad request"})
	}

	var dev Device
	if err := db.Where("token = ?", req.Token).First(&dev).Error; err != nil {
		return c.Status(401).JSON(fiber.Map{"error": "unauthorized"})
	}

	return c.JSON(fiber.Map{
		"shadow_id":  dev.ShadowID,
		"status":     dev.Status,
		"paid_until": dev.PaidUntil,
	})
}

func handleMobileGetServers(c *fiber.Ctx) error {
	auth := c.Get("Authorization")
	if auth == "" {
		return c.Status(401).JSON(fiber.Map{"error": "missing token"})
	}
	tokenStr := strings.TrimPrefix(auth, "Bearer ")
	
	var dev Device
	if err := db.Where("token = ?", tokenStr).First(&dev).Error; err != nil {
		return c.Status(401).JSON(fiber.Map{"error": "invalid token"})
	}

	// Future: Return a list of servers to ping
	return c.JSON([]fiber.Map{
		{
			"id": "eu-ru-bypass-1",
			"ip": os.Getenv("SERVER_IP"),
			"protocol": "vless+reality+vision",
			"load": 24, // fake load for MVP
			"pub": os.Getenv("REALITY_PUBLIC_KEY"),
		},
	})
}

func handleMobileGetConfig(c *fiber.Ctx) error {
	auth := c.Get("Authorization")
	if auth == "" {
		return c.Status(401).JSON(fiber.Map{"error": "missing token"})
	}
	tokenStr := strings.TrimPrefix(auth, "Bearer ")
	
	var dev Device
	if err := db.Where("token = ?", tokenStr).First(&dev).Error; err != nil {
		return c.Status(401).JSON(fiber.Map{"error": "invalid token"})
	}

	// Check if payment active
	if dev.PaidUntil == nil || dev.PaidUntil.Before(time.Now()) {
		// MVP: We'll allow free tier or just 1 hour demo if expired
		// return c.Status(403).JSON(fiber.Map{"error": "subscription expired"})
	}

	// Generate a unique Xray key for this device if not exists
	var vpnUser User
	err := db.Where("status = ? AND tg_id = ?", "active", int64(dev.ID)).First(&vpnUser).Error
	if err != nil {
		// Create a new key binding `dev.ID` to `TgID` (repurposed field for now)
		newUUID := uuid.New().String()
		vpnUser = User{
			UUID:      newUUID,
			Status:    "active",
			TgID:      int64(dev.ID),
			CreatedAt: time.Now(),
		}
		db.Create(&vpnUser)
		xrayManager.AddUser(newUUID, "dev_"+newUUID[:6])
	}

	vlessURL := fmt.Sprintf(
		"vless://%s@%s:443?type=tcp&security=reality&pbk=%s&fp=chrome&sni=addons.mozilla.org&sid=%s&spx=%%2F&flow=xtls-rprx-vision#VPN-%s",
		vpnUser.UUID, os.Getenv("SERVER_IP"), os.Getenv("REALITY_PUBLIC_KEY"), os.Getenv("REALITY_SHORT_ID"), dev.ShadowID[:6],
	)

	return c.JSON(fiber.Map{
		"config_url": vlessURL,
		"protocol":   "vless_reality",
	})
}
